#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@webdav[-1]
	add ucitrack webdav
	set ucitrack.@webdav[-1].init=webdav
	commit ucitrack
EOF

uci delete firewall.webdav
uci add firewall rule 
uci rename firewall.@rule[-1]="webdav"
uci set firewall.@rule[-1].name="webdav"
uci set firewall.@rule[-1].target="ACCEPT"
uci set firewall.@rule[-1].src="wan"
uci set firewall.@rule[-1].proto="tcp"
uci set firewall.@rule[-1].dest_port="6378"
uci commit firewall
rm -f /tmp/luci-indexcache
exit 0
